development:
  settings:
    name: Ma.gnolia
    domain: localhost:3000
    session_key: _magnolia_session
    secret: 1138371c71fe2f4f6769090e9fa0d7314b4febcc1c1966f9c83e16a3c880e0ca396cbb37e9ce53bbefc2417cb7363d7127200d51f16b9aeda033dbc3600c63fc
    forgery_secret: b8029fa60066bb90d7fb4e68265a112b
    admin_email: support@gnolia.com
    new_user_invite_limit: 5
    max_user_invite_limit: 100
  rest_auth:
    site_key: e587f9d09baa59c920b9ee97ac70f58b3c51356c
    stretches: 10
  mail:
    address: mail.gnolia.com
    port: 25
    domain: ma.gnolia.com
    authentication: :login
    user_name: support@gnolia.com
    password: emailaccountpassword
    sender: support@gnolia.com
test:
  settings:
    name: Ma.gnolia
    domain: localhost:3000
    session_key: _magnolia_session
    secret: 1138371c71fe2f4f6769090e9fa0d7314b4febcc1c1966f9c83e16a3c880e0ca396cbb37e9ce53bbefc2417cb7363d7127200d51f16b9aeda033dbc3600c63fc
    forgery_secret: b8029fa60066bb90d7fb4e68265a112b
    admin_email: support@gnolia.com
    new_user_invite_limit: 5
    max_user_invite_limit: 100
  rest_auth:
    site_key: e587f9d09baa59c920b9ee97ac70f58b3c51356c
    stretches: 10
  mail:
    address: mail.gnolia.com
    port: 25
    domain: ma.gnolia.com
    authentication: :login
    user_name: support@gnolia.com
    password: emailaccountpassword
    sender: support@gnolia.com
production:
  settings:
    name: Ma.gnolia
    domain: mail.gnolia.com
    session_key: _magnolia_session
    secret: 1138371c71fe2f4f6769090e9fa0d7314b4febcc1c1966f9c83e16a3c880e0ca396cbb37e9ce53bbefc2417cb7363d7127200d51f16b9aeda033dbc3600c63fc
    forgery_secret: b8029fa60066bb90d7fb4e68265a112b
    admin_email: support@gnolia.com
    new_user_invite_limit: 5
    max_user_invite_limit: 100
  rest_auth:
    site_key: e587f9d09baa59c920b9ee97ac70f58b3c51356c
    stretches: 10
  mail:
    address: mail.yourapplication.com
    port: 25
    domain: ma.gnolia.com
    authentication: :login
    user_name: support@gnolia.com
    password: emailaccountpassword
    sender: support@gnolia.com