# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: a2821daffa29277398ee7076f96cc36b
  secret_key: 417b16666a85919d69c924c0c8fe2761
  canvas_page_name: mag2dev
  callback_url: http://dev.gnolia.com:8888
  pretty_errors: true
  tunnel:
    public_host_username: jclark
    public_host: dev.gnolia.com
    public_port: 8888
    local_port: 3000

test:
  api_key: a2821daffa29277398ee7076f96cc36b
  secret_key: 417b16666a85919d69c924c0c8fe2761
  canvas_page_name: mag2dev
  callback_url: http://dev.gnolia.com:8888
  tunnel:
    public_host_username: jclark
    public_host: dev.gnolia.com
    public_port: 8888
    local_port: 3000

production:
  api_key: a2821daffa29277398ee7076f96cc36b
  secret_key: 417b16666a85919d69c924c0c8fe2761
  canvas_page_name: mag2dev
  callback_url: http://dev.gnolia.com:8888
  tunnel:
    public_host_username: jclark
    public_host: dev.gnolia.com
    public_port: 8888
    local_port: 3000
